// Generated by CoffeeScript 1.8.0
(function() {
  var Server, debug, server,
    __slice = [].slice;

  debug = require('debug')('flux-app');

  Server = (function() {
    function Server(options) {
      var _ref;
      this.options = options;
      this.port = this.options.port;
      this.environment = this.options.environment;
      if ('boolean' === typeof this.options.debug) {
        this.debugEnable = this.options.debug;
      } else {
        this.debugEnable = (_ref = this.environment === 'development') != null ? _ref : true;
      }
    }

    Server.prototype.run = function() {
      if (this.environment === 'development') {
        return debug('start server in development environment');
      }
    };

    Server.prototype.debug = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.debugEnable) {
        return debug.apply(null, args);
      }
    };

    return Server;

  })();

  module.exports = server = function(options) {
    server = new Server(options);
    return server.run();
  };

}).call(this);
