// Generated by CoffeeScript 1.8.0
(function() {
  var AppBase, ClientApp, debug, path,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  path = require('path');

  AppBase = require('./app_base');

  debug = require('debug')('FluxApp');

  ClientApp = (function(_super) {
    __extends(ClientApp, _super);

    function ClientApp() {
      return ClientApp.__super__.constructor.apply(this, arguments);
    }

    return ClientApp;

  })(AppBase);

  module.exports = function(options) {
    return new ClientApp(options);
  };

}).call(this);
