// Generated by CoffeeScript 1.8.0
(function() {
  var MakeMiddleware, Middleware, debug;

  debug = require('debug')('FluxApp:Middleware');

  Middleware = (function() {
    function Middleware(context, callback) {
      this.callback = callback.bind(context);
    }

    Middleware.prototype.attach = function(req, res, next) {
      this.req = req;
      this.res = res;
      return this.next = next;
    };

    Middleware.prototype.expose = function(hash, name) {
      return this.res.expose(hash, name);
    };

    Middleware.prototype.getPath = function() {
      return this.req.path;
    };

    Middleware.prototype.render = function(layout, options, callback) {
      debug('Rendering application into layout');
      return this.res.render(layout, options, (function(_this) {
        return function(err, markup) {
          callback(err);
          debug('Sending markup');
          _this.res.send(markup);
          return _this.next(err);
        };
      })(this));
    };

    Middleware.prototype.run = function() {
      return this.callback(this);
    };

    return Middleware;

  })();

  MakeMiddleware = function(context, callback) {
    var middleware;
    middleware = null;
    return function(req, res, next) {
      if (middleware == null) {
        middleware = new Middleware(context, callback);
      }
      middleware.attach(req, res, next);
      return middleware.run();
    };
  };

  module.exports = MakeMiddleware;

}).call(this);
