// Generated by CoffeeScript 1.8.0
(function() {
  var Router, Routes, debug;

  Routes = require('routes');

  debug = require('debug')('FluxApp:Routes');

  Router = (function() {
    function Router(file) {
      var config;
      this.router = Routes();
      debug('load routes file: ' + file);
      config = this.loadRouterConfig(file);
      debug('start building routes');
      this.buildRouter(config);
      debug('end building routes');
    }

    Router.prototype.loadRouterConfig = function(configFile) {
      this.config = require(configFile);
      return this.config;
    };

    Router.prototype.buildRouter = function(config) {
      var key, route, _results;
      debug('load routes', config);
      _results = [];
      for (key in config) {
        if (config.hasOwnProperty(key)) {
          route = config[key];
          debug('register route with' + key);
          _results.push(this.router.addRoute(key, route));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Router.prototype.match = function(path) {
      return this.router.match(path);
    };

    return Router;

  })();

  module.exports = Router;

}).call(this);
