// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    capitalize: function(string) {
      var strs;
      strs = string.split(/-|_|\s/);
      return strs.map(function(s) {
        return s.substr(0, 1).toUpperCase() + s.substring(1).toLowerCase();
      });
    }
  };

}).call(this);
